Recover latest changes and updates before PR

diff --git a/electronic-side/MqttRestApp/Dockerfile b/electronic-side/MqttRestApp/Dockerfile
--- a/electronic-side/MqttRestApp/Dockerfile
+++ b/electronic-side/MqttRestApp/Dockerfile
@@ -3,12 +3,12 @@ FROM maven:3.9.9-eclipse-temurin-21 AS builder
 WORKDIR /app
 
 COPY pom.xml .
-
 RUN mvn dependency:go-offline -B
 
 COPY src ./src
 
-RUN mvn clean package -DskipTests
+
+RUN mvn clean package -DskipTests || { echo "Build failed"; exit 1; }
 
 FROM openjdk:21-jdk AS runner
 
